baseURL = "https://wuyangzz.github.io/"
languageCode = "zh-cn"
title = "wuyangzz"
theme = "hugo-PaperMod"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "博客"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3


[params]
    since = 2020
    author = "wuyangzz"                           # Author's name
    avatar = "/images/me/avatar.jpeg"           # Author's avatar
    subtitle = "我会更好，因为我没有停止"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    #license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "wuyangzz"
    Email   = "783744175@qq.com"

